name: Build addon zip

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # pull the repository (required)
      - uses: actions/checkout@v1

      # install and run Luacheck
      - name: Install and run Luacheck
        run: |
          sudo apt-get install luarocks
          luarocks install --local luacheck
          exec /home/runner/.luarocks/bin/luacheck Shitlist/*.lua --no-color --config ./Shitlist/.luacheckrc -q

      # run release.sh with arguments
      - name: Create Package
        uses: BigWigsMods/packager@master
        with:
          args: release.sh -g 1.13.2 -p 344967
      
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
