name: Build addon zip

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install and run Luacheck
        run: |
          sudo apt-get install luarocks
          luarocks install --local luacheck
          /home/runner/.luarocks/bin/luacheck . --no-color -q

      - name: Get the packager
        run: |
          curl -s https://raw.githubusercontent.com/mooreatv/packager/master/release.sh > ./release.sh
          chmod 755 ./release.sh

      - name: Create Classic Package
        run: ./release.sh -g 1.13.2 -m pkgmeta.yaml -p 344967
        env:
         CF_API_KEY: ${{ secrets.CF_API_KEY }}
         GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}
         WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}

      - name: Create BfA Package
        run: ./release.sh -m pkgmeta.yaml -p 344967
        env:
         CF_API_KEY: ${{ secrets.CF_API_KEY }}
         GITHUB_OAUTH: ${{ secrets.GITHUB_OAUTH }}

      - uses: Limmek/Shitlist@master
        with:
          name: DynamicBoxerBuild-${{ github.sha }}
          path: .release/
