name: Lint
on: 
  workflow_dispatch:
  
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: wow-lint
        uses: davidcraig/action-wow-lint@v1.0.1
        with:
            path-to-files: '*.lua'
