name: Package and release

on:
  workflow_dispatch:
#  push:
#    tags:
#      - "**"

defaults:
  run:
    working-directory: ./Shitlist

# a workflow is built up as jobs, and within these jobs are steps
jobs:

  # "release" is a job, you can name it anything you want
  release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Package and release
        uses: BigWigsMods/packager@v2
        with:
          args: -S -w 0 -a 0 -p 0
