name: Update Interface version(s)

on:
  schedule:
    - cron: '0 12 * * *'
  push:

defaults:
  run:
    working-directory: ./Shitlist

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Update TOC Interface version
        uses: p3lim/toc-interface-updater@v2

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update Interface version
          #body: 
          commit-message: Update Interface version
          branch: interface-version
          delete-branch: true
